sudo: required
services:
    - docker

before_install:
    - docker build -t docker_myreact -f Dockerfile.dev .

script:
    - docker run -e CI=true docker_myreact npm run test

deploy:
  provider: elasticbeanstalk
  #access_key_id: $AWSN_ACCESS_KEY_ID
  #secret_access_key: "$AWSN_ACCESS_KEY_ID"

  access_key_id: $AWSN_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "ap-south-1"
  app: "reactapptwo"
  env: "Reactapptwo-env"
  bucket_name: "elasticbeanstalk-ap-south-1-517491539969"
  bucket_path: "myReactAppDocker"
  on:
    branch: master